[FEC] Adding support for vs testing for SAI_PORT_ATTR_AUTO_NEG_FEC_MODE_OVERRIDE
dgsudharsan/sonic-sairedis pull request #7
Opened 2023-08-02 15:38 UTC by dgsudharsan

Adding support to test SAI_PORT_ATTR_AUTO_NEG_FEC_MODE_OVERRIDE. We need to test two flows one with attribute supported and one without.
Added logic where MLNX2700 has support for the attribute wheile BCM56850 doesn't have support
Added UT to verify.

2023-08-03 08:37 UTC, Junchao-Mellanox requested changes

2023-08-03 08:37 UTC, Junchao-Mellanox commented on vslib/VirtualSwitchSaiInterface.cpp
>      return SAI_STATUS_SUCCESS;
need remove this line?

2023-08-03 21:36 UTC, dgsudharsan commented on vslib/VirtualSwitchSaiInterface.cpp
>      return SAI_STATUS_SUCCESS;
Done

2023-08-04 00:17 UTC, Junchao-Mellanox approved these changes

2023-08-04 05:08 UTC, closed without merging